eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9091

spring:
  application:
    name: product-service

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/productDB